name: b3Fireworks
main: b3suite.Fireworks.b3Fireworks
version: 3.2
commands:
  givefw:
    description: Spawn fireworks
    usage: /givefw colors type special amount
    permission: command.givefw
    aliases: [gfw]
  launchfw:
    description: Launch firework
    usage: /launchfw colors type special
    permission: command.launchfw
    aliases: [lfw, fw]
  givefwplayer:
    description: Spawn fireworks for another player
    usage: /givefwplayer playername colors type special amount
    permission: command.givefwplayer
    aliases: [gfwp]
permissions:
  b3fireworks.*:
    description: All commands from b3Fireworks
    default: op
    children:
      command.givefw: true
      command.launchfw: true
      command.givefwplayer: true
  command.givefw:
    description: Allows players to use /givefw
    default: op
  command.launchfw:
    description: Allows players to use /launchfw
    default: op
  command.givefwplayer:
    description: Allows players to use /givefwplayer
    default: op
